name: Destroy Infrastructure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0 # Specify your Terraform version here

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1 # Specify your AWS region here

      - name: Terraform Init
        run: terraform init
        working-directory: challenge-3/
        
        
      - name: Terraform Destroy sg-ingress
        run: terraform destroy -auto-approve -target module.nlb.aws_vpc_security_group_ingress_rule.asg-nlb-ingress
        working-directory: challenge-3/

      - name: Terraform Destroy sg-egress
        run: terraform destroy -auto-approve -target module.nlb.aws_vpc_security_group_egress_rule.asg-nlb-egress
        working-directory: challenge-3/

      - name: Terraform Destroy nlb-sg
        run: terraform destroy -auto-approve -target module.nlb.aws_security_group.nlb-sg
        working-directory: challenge-3/

      - name: Terraform Destroy tg
        run: terraform destroy -auto-approve -target module.nlb.aws_lb_target_group
        working-directory: challenge-3/
        
      - name: Terraform Destroy lb listener
        run: terraform destroy -auto-approve -target module.nlb.aws_lb_listener
        working-directory: challenge-3/

      - name: Terraform Destroy lb 
        run: terraform destroy -auto-approve -target module.nlb.aws_lb.this
        working-directory: challenge-3/

      - name: Terraform Destroy asg vpc
        run: terraform destroy -auto-approve -target module.asg -target module.vpc
        working-directory: challenge-3/
