# This workflow will setup terraform and validate, and plan  AWS infrastructure, mainly network resources. 
# it will generate a terraform graph

name: Validate Infrastructure

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0 # Specify your Terraform version here

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1 # Specify your AWS region here

      - name: Terraform Init
        run: terraform init
        working-directory: challenge-3/

      - name: Terraform Validate
        run: terraform validate 
        working-directory: challenge-3/